# Generated by Django 3.2.8 on 2021-11-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JigyasaApp', '0006_sharenotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('start_url', models.CharField(default='', max_length=6000)),
                ('join_url', models.CharField(default='', max_length=6000)),
                ('meeting_password', models.CharField(default='', max_length=600)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JigyasaApp.staffs')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JigyasaApp.subjects')),
            ],
        ),
    ]
